name: steeloverseer
version: '2.0.1.0'
license: BSD3
license-file: LICENSE
maintainer: schell.scivally@synapsegrop.com
stability: stable
github: schell/steeloverseer
synopsis: A file watcher and development tool.
description: >
    A command line tool that responds to filesystem events.
    Allows the user to automatically execute commands after
    files are added or updated. Watches files using regular
    expressions.
category: Development
author:
  - Schell Scivally
  - Mitchell Rosen
extra-source-files:
  - README.md

flags:
  mtl-compat:
    description: Depend on mtl-compat for Control.Monad.Except
    manual: false
    default: false

ghc-options: -Wall

dependencies:
  - base >= 4.0 && < 6.0
  - bytestring >= 0.10
  - regex-tdfa >= 1.2
  - semigroups >= 0.16
  - stm >= 2.4
  - text >= 1.2
  - yaml >= 0.8

library:
  source-dirs: src
  dependencies:
    - aeson >= 0.8
    - ansi-terminal >= 0.6.2
    - async >= 2.0
    - containers >= 0.5
    - mtl >= 2.1
    - process >= 1.2
  when:
    - condition: flag(mtl-compat)
      dependencies:
        - mtl-compat >= 0.2

executables:
  sos:
    main: Main.hs
    source-dirs: app
    dependencies:
      - steeloverseer
      - directory >= 1.2
      - fsnotify >= 0.2
      - filepath >= 1.3
      - optparse-applicative >= 0.11
    when:
      - condition: os(darwin)
        dependencies: hfsevents >= 0.1.3
    ghc-options: -threaded
